### PR TITLE
feat: Adding initial Terraform  resources to manage GCP

### PR DESCRIPTION
**Pull request by tfhartmann**
This adds the GCP resources needed to run backstage, so that the app's dependencies can be managed in the monorepo  and changes can take place our of a single PR. 

---

## Write Good Commit Messages

[The seven rules of a great Git commit message](https://cbea.ms/git-commit/)

* Separate subject from body with a blank line
* Limit the subject line to 50 characters
* Capitalize the subject line
* Do not end the subject line with a period
* Use the imperative mood in the subject line
* Wrap the body at 72 characters
* Use the body to explain what and why vs. how

### CODE REVIEW

**Comment by tfhartmann** [comment]
atlantis plan -- -target= google_project_service.api_services

**Comment by tfhartmann** [comment]
atlantis plan -- -target=google_project_service.api_services

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan -p production -- -target=google_project_service.api_services

**Comment by tfhartmann** [comment]
atlantis plan -p production -- -target=google_project_service.api_services

**Comment by tfhartmann** [comment]
atlantis plan -p production -- -target=google_project_service.api_services

**Comment by tfhartmann** [comment]
atlantis apply -p production

**Comment by tfhartmann** [comment]
atlantis plan

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis plan

**Comment by tfhartmann** [comment]
atlantis plan

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development

**Comment by tfhartmann** [comment]
atlantis plan  -p development

**Comment by tfhartmann** [comment]
atlantis plan -p development -- -target= google_storage_bucket.tech-docs

**Comment by tfhartmann** [comment]
atlantis plan -p development -- -target=google_storage_bucket.tech-docs

**Comment by tfhartmann** [comment]
atlantis apply -p development

**Review by coreone — APPROVED** [review]

**Comment by tfhartmann** [comment]
atlantis plan -p production -- -target=google_secret_manager_secret.backstage-bits-credentials

**Comment by tfhartmann** [comment]
atlantis apply -p production

**Comment by tfhartmann** [comment]
atlantis plan

**Comment by tfhartmann** [comment]
atlantis apply -p production

**Comment by tfhartmann** [comment]
atlantis apply

**Pull request merged**
